import { Body, Controller, Get, Param, Patch, Post, Query, UseGuards } from '@nestjs/common';
import { Role } from '@prisma/client';
import { KnowledgeService } from './knowledge.service';
import { UpdateArticleDto } from './dto/update-article.dto';
import { RejectArticleDto } from './dto/reject-article.dto';
import { SubmitFeedbackDto } from './dto/submit-feedback.dto';
import { SendBackArticleDto } from './dto/send-back-article.dto';
import { JwtAuthGuard } from '../../common/guards/jwt-auth.guard';
import { RolesGuard } from '../../common/guards/roles.guard';
import { Roles } from '../../common/decorators/roles.decorator';
import { CurrentUser, AuthenticatedUser } from '../../common/decorators/current-user.decorator';

// No POST / here — articles are never created directly by a client. They're
// auto-generated by CasesService.confirm() when a case closes (Charter
// Section 9.1) and only ever edited/submitted/reviewed after that.
@UseGuards(JwtAuthGuard, RolesGuard)
@Controller('knowledge')
export class KnowledgeController {
  constructor(private readonly knowledgeService: KnowledgeService) {}

  @Roles(Role.EXPERT)
  @Get('mine')
  listMine(@CurrentUser() user: AuthenticatedUser) {
    return this.knowledgeService.listMine(user.userId);
  }

  @Roles(Role.MODERATOR, Role.ADMINISTRATOR)
  @Get('pending')
  listPendingReview() {
    return this.knowledgeService.listPendingReview();
  }

  // Open to any authenticated role — farmers are the primary audience, but
  // there's no reason to gate reading published advisory content further.
  @Get('published')
  listPublished(@Query('categoryId') categoryId?: string) {
    return this.knowledgeService.listPublished(categoryId);
  }

  @Roles(Role.MODERATOR, Role.ADMINISTRATOR)
  @Get('flagged')
  listFlagged() {
    return this.knowledgeService.listFlagged();
  }

  @Get('bookmarks')
  listBookmarked(@CurrentUser() user: AuthenticatedUser) {
    return this.knowledgeService.listBookmarked(user.userId);
  }

  @Get('recently-viewed')
  listRecentlyViewed(@CurrentUser() user: AuthenticatedUser) {
    return this.knowledgeService.listRecentlyViewed(user.userId);
  }

  // Kept below the fixed /mine, /pending, /published, /flagged, /bookmarks,
  // /recently-viewed routes deliberately — NestJS matches in declaration
  // order, and :id would otherwise swallow those static paths as article IDs.
  @Get(':id')
  getById(@Param('id') id: string, @CurrentUser() user: AuthenticatedUser) {
    return this.knowledgeService.getById(id, { userId: user.userId, role: user.role as Role });
  }

  @Roles(Role.EXPERT)
  @Patch(':id')
  updateDraft(@Param('id') id: string, @Body() dto: UpdateArticleDto, @CurrentUser() user: AuthenticatedUser) {
    return this.knowledgeService.updateDraft(id, user.userId, dto);
  }

  @Roles(Role.EXPERT)
  @Post(':id/submit')
  submit(@Param('id') id: string, @CurrentUser() user: AuthenticatedUser) {
    return this.knowledgeService.submit(id, user.userId);
  }

  @Roles(Role.MODERATOR, Role.ADMINISTRATOR)
  @Post(':id/approve')
  approve(@Param('id') id: string, @CurrentUser() user: AuthenticatedUser) {
    return this.knowledgeService.approve(id, user.userId);
  }

  @Roles(Role.MODERATOR, Role.ADMINISTRATOR)
  @Post(':id/reject')
  reject(@Param('id') id: string, @Body() dto: RejectArticleDto, @CurrentUser() user: AuthenticatedUser) {
    return this.knowledgeService.reject(id, user.userId, dto);
  }

  // Open to any authenticated role, same reasoning as GET /published —
  // Helpful/Not Helpful + rating + comment (Charter Section 10.1).
  @Post(':id/feedback')
  submitFeedback(@Param('id') id: string, @Body() dto: SubmitFeedbackDto, @CurrentUser() user: AuthenticatedUser) {
    return this.knowledgeService.submitFeedback(id, user.userId, dto);
  }

  @Get(':id/feedback')
  getFeedbackSummary(@Param('id') id: string, @CurrentUser() user: AuthenticatedUser) {
    return this.knowledgeService.getFeedbackSummary(id, user.userId);
  }

  @Roles(Role.MODERATOR, Role.ADMINISTRATOR)
  @Post(':id/clear-flag')
  clearFlag(@Param('id') id: string, @CurrentUser() user: AuthenticatedUser) {
    return this.knowledgeService.clearFlag(id, user.userId);
  }

  @Roles(Role.MODERATOR, Role.ADMINISTRATOR)
  @Post(':id/send-back')
  sendBack(@Param('id') id: string, @Body() dto: SendBackArticleDto, @CurrentUser() user: AuthenticatedUser) {
    return this.knowledgeService.sendBackForRevision(id, user.userId, dto);
  }

  @Post(':id/bookmark')
  toggleBookmark(@Param('id') id: string, @CurrentUser() user: AuthenticatedUser) {
    return this.knowledgeService.toggleBookmark(id, user.userId);
  }

  @Get(':id/bookmark')
  isBookmarked(@Param('id') id: string, @CurrentUser() user: AuthenticatedUser) {
    return this.knowledgeService.isBookmarked(id, user.userId);
  }
}
